import React, { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { FileText, ChevronDown } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import PageWrapper from '../components/ui/PageWrapper';
import { subtitleApi } from '../services/api';
import { isYouTubeUrl, downloadBlob } from '../utils/helpers';

const SubtitleDownload = () => {
  const [url, setUrl] = useState('');
  const [lang, setLang] = useState('en');
  const [format, setFormat] = useState('srt');
  const [isDownloading, setIsDownloading] = useState(false);
  const validUrl = isYouTubeUrl(url) ? url : '';

  const { data: langData, isLoading: langsLoading } = useQuery({
    queryKey: ['subtitle-langs', validUrl],
    queryFn: () => subtitleApi.getLanguages(validUrl).then((r) => r.data.data),
    enabled: !!validUrl,
  });

  const languages = langData?.languages || [];

  const handleDownload = async () => {
    if (!validUrl) return;
    setIsDownloading(true);
    toast.loading('Fetching subtitles...', { id: 'dl' });
    try {
      const res = await subtitleApi.download(url, lang, format);
      downloadBlob(res.data, `subtitles_${lang}.${format}`);
      toast.success('Subtitles downloaded!', { id: 'dl' });
    } catch (err) {
      toast.error(err?.response?.data?.message || 'No subtitles available', { id: 'dl' });
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <PageWrapper>
      <Helmet>
        <title>YouTube Subtitle Downloader - SRT VTT - XRSave-YT</title>
        <meta name="description" content="Download YouTube subtitles and captions in SRT, VTT, and plain text formats." />
      </Helmet>
      <div className="max-w-2xl mx-auto px-4 pt-28 pb-20">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-14 h-14 bg-gradient-to-br from-green-500 to-emerald-600 rounded-2xl mb-4">
            <FileText className="w-7 h-7 text-white" />
          </div>
          <h1 className="font-display text-3xl sm:text-4xl font-bold">Subtitle Downloader</h1>
          <p className="text-gray-400 mt-2">Download captions in SRT, VTT or plain text</p>
        </div>
        <div className="space-y-4">
          <div className="card p-4">
            <label className="block text-xs text-gray-500 mb-2 font-medium uppercase tracking-wider">YouTube URL</label>
            <input type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://youtube.com/watch?v=..." className="input-field" />
          </div>

          {languages.length > 0 && (
            <div className="card p-4 space-y-3">
              <div>
                <label className="block text-xs text-gray-500 mb-2 font-medium uppercase tracking-wider">Language</label>
                <div className="relative">
                  <select value={lang} onChange={(e) => setLang(e.target.value)} className="input-field appearance-none pr-10">
                    {languages.map((l) => (
                      <option key={l.code} value={l.code}>{l.name}{l.isAutoGenerated ? ' (Auto)' : ''}</option>
                    ))}
                  </select>
                  <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 pointer-events-none" />
                </div>
              </div>
              <div>
                <label className="block text-xs text-gray-500 mb-2 font-medium uppercase tracking-wider">Format</label>
                <div className="flex gap-2">
                  {['srt', 'vtt', 'txt'].map((f) => (
                    <button key={f} onClick={() => setFormat(f)}
                      className={`flex-1 py-2.5 rounded-xl border text-sm font-medium transition-all ${format === f ? 'border-brand-500 bg-brand-600/10 text-white' : 'border-dark-500 bg-dark-700 text-gray-400 hover:border-dark-400'
                        }`}
                    >
                      .{f.toUpperCase()}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}

          {langsLoading && <div className="card p-4"><div className="skeleton h-10 w-full rounded-xl" /></div>}

          <button onClick={handleDownload} disabled={!validUrl || isDownloading} className="w-full btn-primary py-4 disabled:opacity-50 disabled:cursor-not-allowed">
            {isDownloading ? 'Downloading...' : 'Download Subtitles'}
          </button>
        </div>
      </div>
    </PageWrapper>
  );
};

export default SubtitleDownload;
